[tool.poetry]
name = "py-web-hw-4"
version = "0.1.0"
description = "Python WEB homework 4"
authors = ["Sergiy-Glookh <sglookh@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
